steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    script: >
      docker buildx build --progress=rawjson
      -t us-west2-docker.pkg.dev/$PROJECT_ID/dimitriye98/quiet-star:$BRANCH_NAME
      -t us-west2-docker.pkg.dev/$PROJECT_ID/dimitriye98/quiet-star:$BRANCH_NAME-$SHORT_SHA
      --cache-from type=registry,ref=us-west2-docker.pkg.dev/$PROJECT_ID/dimitriye98/quiet-star:$BRANCH_NAME
      --cache-from type=registry,ref=us-west2-docker.pkg.dev/$PROJECT_ID/dimitriye98/quiet-star:main
      --cache-to type=inline
      .
images:
  - us-west2-docker.pkg.dev/$PROJECT_ID/dimitriye98/quiet-star:$BRANCH_NAME
  - us-west2-docker.pkg.dev/$PROJECT_ID/dimitriye98/quiet-star:$BRANCH_NAME-$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
